app:
  timezone: "Asia/Shanghai"

crawler:
  request_interval: 1000

report:
  mode: "current"
  rank_threshold: 10
  sort_by_position_first: false
  max_news_per_keyword: 8
  reverse_content_order: true

platforms:
  - id: "xiaohongshu"
    name: "小红书"
  - id: "douyin"
    name: "抖音"
